allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.102.1'
  - '@tanstack/react-query@5.102.1'

shamefullyHoist: true
shellEmulator: true

strictPeerDependencies: false
trustPolicy: no-downgrade
trustPolicyExclude:
  - ua-parser-js@0.7.41
  - ua-parser-js@1.0.41
  - semver@6.3.1
